# Settings for code style formatting - activate code styling with "pre-commit install" in your cmd/terminal
[tool.ruff]
line-length = 120
target-version = "py311"

[mypy]
ignore_missing_imports = true
exclude = ["data"]
pretty = true

[mirrors-mypy]
ignore_missing_imports = true
exclude = ["data"]
pretty = true

[tool.interrogate]
ignore-module = true
ignore-init-method = true
ignore-init-module = true
ignore-property-decorators = true
ignore-magic = true
ignore-nested-classes = true
fail-under = 80
verbose = 2
exclude = ["data"]

[tool.setuptools_scm]
version_file = "_version.py"
